version: '3.8'

services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 5000:5000
        volumes:
            - .:/app
        depends_on: 
            - db

    db:
        image: mysql:latest
        restart: always
        environment:
            MYSQL_DATABASE: test
            MYSQL_USER: test
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
        volumes:
            - .:/app
        ports:
            - 5405:5432