version: '3.8'

services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 5000:5000
        volumes:
            - .:/app
        depends_on: 
            - db

    db:
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_DB: test
            POSTGRES_USER: test
            POSTGRES_PASSWORD: test
        volumes:
            - .:/app
        ports:
            - 5405:5432