name: Docker

on: push

env:
  IMAGE_NAME: reval-build

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  build_and_push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry
        run: doctl registry login

      - name: Tag image with the fully qualified destination path
        run: docker tag $(echo $IMAGE_NAME) ${{ secrets.DIGITALOCEAN_REGISTRY }}/$(echo $IMAGE_NAME)

      - name: Push image to DigitalOcean Container Registry
        run: docker push ${{ secrets.DIGITALOCEAN_REGISTRY }}/$(echo $IMAGE_NAME)

  # deploy:
  #   runs-on: ubuntu-latest
  #   if: github.event_name == 'push'
  #   needs: build_and_push

  #   steps:
  #     - name: Deploy to Digital Ocean droplet via SSH action
  #       uses: appleboy/ssh-action@v0.1.3
  #       with:
  #         HOST: ${{ secrets.HOST }}
  #         USERNAME: ${{ secrets.USERNAME }}
  #         KEY: ${{ secrets.SSHKEY }}
  #         envs: IMAGE_NAME,REGISTRY,GITHUB_SHA,COMMAND
  #         script: |
  #           # Stop running container
  #           docker stop $(echo $IMAGE_NAME)

  #           # Remove old container
  #           docker rm $(echo $IMAGE_NAME)

  #           # Run a new container from a new image
  #           docker run -d \
  #           --restart always \
  #           --env-file .env \
  #           -p 8000:8000 \
  #           --name $(echo $IMAGE_NAME) \
  #           $(echo $DIGITALOCEAN_REGISTRY)/$(echo $IMAGE_NAME):$(echo $GITHUB_SHA | head -c7) $(echo $COMMAND)
